---
abstract: 'an implementation of Concurrent Revisions'
author:
  - 'Tomoki Aonuma <uasi@99cm.org>'
build_requires:
  ExtUtils::MakeMaker: 6.57
  Test::Fatal: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.57
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ConcurrentRev
no_index:
  directory:
    - inc
    - t
requires:
  Attribute::Handlers: 0
  Coro: 0
  Devel::GlobalDestruction: 0
  Devel::Refcount: 0
  Mo: 0
  Try::Tiny: 0
  parent: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
